name: Check orders confirmation

on:
  push:
    branches: [main]
  schedule:
  - cron: "0,15,30,45 * * * 1-5"


jobs:
  check:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: 
          node-version: '20.x'
          cache: 'npm'
      - name: Install dependencies
        run: npm install     
      - name: Run start
        env:
          AIRTABLE_API_KEY: ${{ secrets.AIRTABLE_API_KEY }}
          DODO_CLIENT_ID: ${{ secrets.DODO_CLIENT_ID }}
          DODO_CLIENT_SECRET: ${{ secrets.DODO_CLIENT_SECRET }}
          DODO_OAUTH_URI: ${{ secrets.DODO_OAUTH_URI }}
          DODO_SCOPE: ${{ secrets.DODO_SCOPE }}
          DODO_ORDERS_API: ${{ secrets.DODO_ORDERS_API }}
        run: npm run start:check 
        